### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by bmathews**

### CODE REVIEW

**Comment by bmathews** [comment]
@kenwheeler @boygirl This PR adds a basic default render test for all the victory-chart-native components. Thoughts?

**Comment by bmathews** [comment]
Not quite sure what to about these, yet:

image

**Comment by boygirl** [comment]
All the PropTypes errors will go away with an upgrade of `victory-core` in `victory-core-native`. Can you open a separate ticket for the unknown prop warnings?

**Comment by bmathews** [comment]
@boygirl done!

**Comment by kenwheeler** [comment]
This is super dope. Any opinions on whether there is value in pulling the rn-svg mock out into its own thing?

**Comment by boygirl** [comment]
@bmathews this looks good to merge to me. @kenwheeler I think that's a good idea. We'll need it in the other victory-native repos too.

**Pull request merged**
