### PR TITLE
Fix bug with ClipPath not being passed in

### PR DESCRIPTION
**Pull request by brentvatne**
Also remove react-native-svg as a dependency, use peerDependency instead.

### CODE REVIEW

**Comment by boygirl** [comment]
@brentvatne Thanks for helping out. I haven't been as attentive to the native repos as I would like. This PR doesn't quite match up with how clipPath is operating in `victory-chart`. I'll get a correct fix up today though.

**Comment by brentvatne** [comment]
Thanks @boygirl!

re: Removing the react-native-svg hard dependency: We included react-native-svg for an upcoming release of [Exponent](http://getexponent.com/) (should be out later today or tomorrow), and we want people to be able to install and use victory-chart-native. Right now, each of the victory-*-native packages depends on react-native-svg, so we end up with a bunch of copies of it. I think it would be better to set this as a peerDependency.

**Comment by boygirl** [comment]
@brentvatne I think that change makes sense. We've avoided peer dependencies up to now, but I'll check with our infrastructure gurus and see what they say.

**Comment by boygirl** [comment]
Also tracking down a bug with `react-native-svg@4.x.x` + `victory-chart-native`. :/

**Pull request closed without merging**
